/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Civitas.Casilla;
import Civitas.CasillaCalle;
import Civitas.CasillaCarcel;
import Civitas.CasillaImpuesto;
import Civitas.CasillaSorpresa;

public class CasillaView extends javax.swing.JPanel {

    public Casilla casilla;
    /**
     * Creates new form CasillaView
     */
    public CasillaView() {
        initComponents();
    }
    
    public void setCasilla(Casilla cas){
        this.casilla = cas;
        this.Nombre.setText(this.casilla.getNombre());
        
        switch(this.casilla.getTipo()){
            case 0:
                this.Tipo.setVisible(false);
                this.Titulo.setVisible(false);
                this.Valor.setVisible(false);
                this.tipo.setVisible(false);
                this.titulo.setVisible(false);
                this.valor.setVisible(false);
                break;
            case 1:
                this.Tipo.setVisible(true);
                this.Titulo.setVisible(true);
                this.tipo.setVisible(true);
                this.titulo.setVisible(true);
                this.Titulo.setText(this.casilla.toString());
                this.Tipo.setText("Calle");
                
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        tipo = new javax.swing.JLabel();
        Tipo = new javax.swing.JTextField();
        valor = new javax.swing.JLabel();
        Valor = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        Titulo = new javax.swing.JTextField();

        nombre.setText("Nombre:");
        add(nombre);

        Nombre.setText("jTextField1");
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        add(Nombre);

        tipo.setText("Tipo:");
        add(tipo);

        Tipo.setText("jTextField2");
        add(Tipo);

        valor.setText("Valor");
        add(valor);

        Valor.setText("jTextField3");
        add(Valor);

        titulo.setText("Título");
        add(titulo);

        Titulo.setText("jTextField4");
        add(Titulo);
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Tipo;
    private javax.swing.JTextField Titulo;
    private javax.swing.JTextField Valor;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
